### ISSUE TITLE
[META] Recent jobs view improvements

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#117]
**Description**
Space in the recent jobs view is used very inefficiently. We don't show important information (like number of files indexed), and at the same time we use a lot of space to show things that are not important (like actions column).

### Required Features

- [x] #21 Remove job entry from the Recent Jobs page
- [x] #24 Remove the Actions column from the Recent Jobs page
- [x] #20 Show number of detected samples per each job in "Recent Jobs"
