### ISSUE TITLE
[META] Release v1.3

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#233]
A lot of time has passed since the last release. It's time to wrap up, fix pending issues, implement last pressing features and ship a new version.

Issues selected for this release (initially)

- Major missing features:
  - [ ] #23 At least partial user permission model is a common request from bigger organisations. It will also come in handy in the open mquery instance we plan to host.
- Yara upgrade and fixes:
  - [x] #231 Fix regex parsing in yaramod (and wait for a new release to ship it)
  - [x] #100 Support xor ranges (just update the dependency)
- Reported UI issues, including (but not limited to):
  - [x] Better progress reporting (#64, #183, #193)
  - [x] #34
  - [x] #125
  - [x] #195 (triage)
  - [ ] #204
  - [ ] #220 - improve the documentation and user-friendliness of indexing
- Other maintenance:
  - [x] #235
  - [x] #236
