### ISSUE TITLE
[META] Support more features of Yara

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#41]
**Description**
It seems like mquery does not support a lot of the features of yara, which makes it less powerful and blocking the possibility for utilizing mquery for quality hunting of new samples, exploits and more. The limited set of features used by mquery is limiting the user significantly.

### Required Features

**Rules (see also #40)**
- [x] Multiple rules in a query (Issue: #40, Implemented in #55)
- [x] [Referencing other rules](https://yara.readthedocs.io/en/stable/writingrules.html#referencing-other-rules) (Implemented in #55)
- [x] [Private rules](https://yara.readthedocs.io/en/stable/writingrules.html#private-rules) (Implemented in #55)
- [x] [Global rules](https://yara.readthedocs.io/en/stable/writingrules.html#global-rules) (Implemented in #55)

**Strings**
- [x] [Case-insensitive strings](https://yara.readthedocs.io/en/stable/writingrules.html#case-insensitive-strings) -Honor the `nocase` flag  (Issue: #48)
- [x] [Regexes](https://yara.readthedocs.io/en/stable/writingrules.html#regular-expressions) - Don't ignore regexes (Issue: #97, also #18)
- [x]  [Support both ascii and wide string stogether](https://yara.readthedocs.io/en/stable/writingrules.html#wide-character-strings) (Issue: #50)
- [x] [Support full words](https://yara.readthedocs.io/en/stable/writingrules.html#searching-for-full-words) (Issue: #49)
- [x] [Support the XOR modifyer for strings](https://yara.readthedocs.io/en/stable/writingrules.html#xor-strings) (Issue: #51)
- [x] [Support anonymous variables](https://yara.readthedocs.io/en/stable/writingrules.html#using-anonymous-strings-with-of-and-for-of) (Issue: #45)

**Comment by msm-code** [comment]
I've created few new issues to track string releated problems:

#48 nocase (suprisingly hard)
#49 full words (trivial)
#50 ascii and wide strings together (easy)

And the xor is probably out of scope for now - I fear that the results of prefiltering will probably be useless anyway, and it'll end up as slow as just doing a full scan. I've created a tracking issue for it anyway:

#51 Accelerate xor modifier

**Comment by nazywam** [comment]
🎊

**Comment by msm-code** [comment]
:1st_place_medal:

**Comment by ITAYC0HEN** [comment]
Amazing job, team! you are wonderful
